# Generated by Django 5.0.1 on 2024-01-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerQuery',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('query_type', models.CharField(choices=[('General', 'General Inquiry'), ('Technical', 'Technical Issue'), ('CropInfo', 'Crop Information')], max_length=20)),
                ('crop_information', models.TextField()),
                ('query_subject', models.CharField(choices=[('PestControl', 'Pest Control'), ('Fertilization', 'Fertilization'), ('Disease', 'Crop Disease'), ('Other', 'Other')], max_length=20)),
                ('specific_issue', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.user')),
            ],
            options={
                'db_table': 'Farmer_Query',
            },
        ),
    ]
