# Generated by Django 5.0.1 on 2024-01-15 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0003_farmerquery_latitude_farmerquery_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('rating', models.IntegerField()),
                ('additional_comments', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.user')),
            ],
            options={
                'db_table': 'Feedback_details',
            },
        ),
    ]
