# Generated by Django 5.0.1 on 2024-01-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('query_subject', models.CharField(choices=[('PestControl', 'Pest Control'), ('Fertilization', 'Fertilization'), ('Disease', 'Crop Disease'), ('Other', 'Other')], max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.user')),
            ],
            options={
                'db_table': 'Appointment_details',
            },
        ),
    ]
