# Generated by Django 5.1 on 2025-03-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0007_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='images/crop_predictions/')),
                ('plant_type', models.CharField(max_length=100)),
                ('growth_tips', models.TextField()),
                ('care_tips', models.TextField()),
                ('pesticide_suggestions', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.user')),
            ],
            options={
                'db_table': 'crop_predictions',
            },
        ),
    ]
